@startuml

title __MANAGER's Class Diagram__\n

  namespace org.orgname.app {
    namespace database.manager {
      class org.orgname.app.database.manager.DailySaleEntityManager {
          {static} - database : MysqlDatabase
          + DailySaleEntityManager()
          {static} + getHistorySale()
          {static} + getStatisticTopFuels()
          {static} + getStatisticTopFuelsByDate()
      }
    }
  }
  

  namespace org.orgname.app {
    namespace database.manager {
      class org.orgname.app.database.manager.FirmEntityManager {
          {static} - database : MysqlDatabase
          + FirmEntityManager()
          {static} + getAllFirm()
      }
    }
  }
  

  namespace org.orgname.app {
    namespace database.manager {
      class org.orgname.app.database.manager.FuelEntityManager {
          {static} - database : MysqlDatabase
          {static} - isFuelExists : boolean
          + FuelEntityManager()
          + add_fuel()
          + add_fuel_station()
          + deleteById()
          + deleteFuelById()
          + deleteFuel_Has_StationById()
          {static} + getAllFuels()
          {static} + getAllOnlyFuels()
          + getFuelById()
          {static} + getFuelByStation()
          + getIDfuel()
          + getStaionByName()
          {static} + isIsFuelExists()
          + update_fuel()
          + update_fuel_station()
      }
    }
  }
  

  namespace org.orgname.app {
    namespace database.manager {
      class org.orgname.app.database.manager.StationEntityManager {
          {static} - database : MysqlDatabase
          + StationEntityManager()
          {static} + getAllStations()
      }
    }
  }
  

  namespace org.orgname.app {
    namespace database.manager {
      class org.orgname.app.database.manager.UserEntityManager {
          {static} - isUserExists : boolean
          + UserEntityManager()
          + add_user_account()
          + deleteById()
          + getAll()
          + getById()
          + getByLogin()
          + getByLoginAndPassword()
          {static} + isIsUserExists()
          + update()
      }
    }
  }
  

  org.orgname.app.database.manager.UserEntityManager o-- org.orgname.app.util.MysqlDatabase : database


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
